### ISSUE TITLE
checkpoint files

### ISSUE THREAD

**Issue by kongyanye** [Tom-roujiang/MSAD#1]
Good work! Could you please also share the trained checkpoint files for evaluation purpose and performance comparison?

**Comment by Tom-roujiang** [comment]
> Good work! Could you please also share the trained checkpoint files for evaluation purpose and performance comparison?

Hi, thank you for your interest in our work. I have improved my GitHub repository to make the code cleaner and the details more complete. Some of the pretrained models I provided are available for reference in this Google Drive link. If you have further questions, feel free to let me know. 

https://drive.google.com/drive/folders/1mxFGCcAuEecN0c7MHD12wD4pO2Ej5kLe
